name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
      os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: make clean
      run: make clean
    - name: make purge
      run: make purge
    - name: make
      run: make
      
    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ganjirk/demoapps1:latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
