name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make purge
      run: make purge
    
    - name: make clean
      run: make clean
      
    - name: make
      run: make
      
    - name: Permissions
      run: chmod +x runme
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        dockerfile: ./Dockerfile
        image: ganjirk/demoapps1
        tag: ganjirk/demoapps1:latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
